### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Multielio/mad-creeper#1]
To improve my own coding, I browse other's source code quite often. And while I was browsing your code I had a question regarding the following line:
`if((!(e.getDamager() instanceof Creeper)) && (!( e.getCause() ==EntityDamageEvent.DamageCause.ENTITY_EXPLOSION)))return;`

Why negate both checks **and** use `&&`?
The only time return is executed is when `e.getDamager() instanceof Creeper` returns false **and** `e.getCause() ==EntityDamageEvent.DamageCause.ENTITY_EXPLOSION)` returns false. In any other case, the code is executed. So wouldn't it be more readable to use `||` and negate the whole thing? 

Also, you can execute the method `setHealth()` on any [Damageable entity](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Damageable.html). This may be more reliable that `Damageable#damage`

Thank you for your time.

**Comment by Multielio** [comment]
1. No the only time return is executed is: If it is not an explosion and not a creeper.

2. not(A) and not(B) <=> not(A or B)    De Morgan's laws
So no problem.

3. Thanks for the setHealth() function I forgot that it existed :)

**Comment by Nuytemans-Dieter** [comment]
Thank you for your answers!
I'm glad this was useful for both of us!!
